version: "3.9"
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=iot
    healthcheck:
      test: ["CMD", "echo", "hello world"]
  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 3000:3000